{{ if .Values.timescaledbExternal.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-timescaledb-passwords
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- $values := urlParse .Values.timescaledbExternal.db_uri }}
  {{- $userInfo := get $values "userinfo" }}
  {{- $userDetails :=  split ":" $userInfo }}
  {{- $user := $userDetails._0 }}
  {{- $password := $userDetails._1 }}
  {{ $user }} : {{ $password | b64enc }}
{{- end -}}