{{ if .Values.timescaledbExternal.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-timescaledb-passwords
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ include "tobs.dburi.user" . }}: {{ include "tobs.dburi.password" . | b64enc }}
{{- end -}}