{{ if .Values.grafana.enabled -}}
{{ if .Values.grafana.sidecar.datasources.enabled }}
{{- $tsEnabled := .Values.grafana.timescale.datasource.enabled -}}
{{- $promEnabled := .Values.grafana.prometheus.datasource.enabled -}}
{{- $anyDataSources := or $tsEnabled $promEnabled -}}
{{ if $anyDataSources -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "1"
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
{{- if $promEnabled }}
      - name: Prometheus
        type: prometheus
        url: {{ tpl .Values.grafana.prometheus.datasource.url . }}
        isDefault: true
        editable: true
        access: proxy
{{- end -}}
{{ if $tsEnabled -}}
{{- $isDefault := not $promEnabled -}}
{{- $hostURL := "" -}}
{{ if .Values.timescaledbExternal.enabled -}}
  {{- $hostURL = include "tobs.dburi.host" . -}}
{{ else -}}
  {{- $host := tpl .Values.grafana.timescale.database.host $ -}}
  {{- $port := .Values.grafana.timescale.database.port | int -}}
  {{- $hostURL = printf "%s:%d" $host $port -}}
{{ end }}
      - name: TimescaleDB
        url: {{ $hostURL }}
        type: postgres
        isDefault: {{ $isDefault }}
        access: proxy
        user: {{ ternary (include "tobs.dburi.user" . ) (.Values.grafana.timescale.database.user ) (.Values.timescaledbExternal.enabled) }}
        database: {{ ternary (include "tobs.dburi.dbname" . ) (.Values.grafana.timescale.database.dbName ) (.Values.timescaledbExternal.enabled) }}
        editable: true
        secureJsonData:
          password: {{ ternary (include "tobs.dburi.password" . ) (.Values.grafana.timescale.database.pass ) (.Values.timescaledbExternal.enabled) }}
        jsonData:
          sslmode: {{ ternary (include "tobs.dburi.sslmode" . ) (.Values.grafana.timescale.database.sslMode ) (.Values.timescaledbExternal.enabled) }}
          postgresVersion: 1000
          timescaledb: true
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
